### ISSUE TITLE
Serer export creates duplicate forge jars

### ISSUE THREAD

**Issue by MxtressMyxx** [DaemonicLabs/Voodoo#11]
After running the server-install jar, there is a forge.jar as well as a forge[version].jar

Instead, there should be only a single jar, with the file name reflecting the forge version, pack name and version:
[packShortName]-[packVersion]-server-forge-[forgeVersion].jar

**Comment by NikkyAI** [comment]
no there should be
becuase forge install will check for that fiel and run again if it does not exist
so the easiest way is to always create a copy of the file i expect it to create
