### ISSUE TITLE
curse dependency resolution should inherit traits from parent entry

### ISSUE THREAD

**Issue by lambdadog** [DaemonicLabs/Voodoo#15]
example:

stellar sky requires stellar API, but when bundled normally, minecraft complains and won't launch, since the latest version of stellar API is ahead of the latest version of stellar sky

theoretically, if I were to grab the release versions of both, it would all be fine, but no matter how i do it, the dependency version of stellar API seems to overwrite the manually added version, and it still grabs the latest (alpha) version

I suppose this also brings up another issue too: that manually added mods should overwrite automatically added mods, so if stellar API is added both as an automatic dependency and manually, the manual addition should take precedent

**Comment by lambdadog** [comment]
for clarification, the dependency always has "curseReleaseTypes: [ALPHA, BETA, RELEASE]" even when the parent that depends on it has "curseReleaseTypes: [RELEASE]"

**Comment by lambdadog** [comment]
actually, even when I copy the link down (jumping through all the hoops needed to for CurseForge) it still somehow manages to translate it over to a CurseForge entry and give me the latest one I don't want??

**Comment by NikkyAI** [comment]
i see that is a issue, this should not happen, are you usin master or rewrite ?
this is long fixed in the rewritten version (https://ci.elytradev.com/job/elytra/job/Voodoo/job/rewrite/)
https://github.com/elytra/Voodoo/blob/rewrite/core/src/main/kotlin/voodoo/provider/Curse.kt#L161-L168

.. i really should merge this back into master asap, but not all features are back yet

**Comment by NikkyAI** [comment]
as far why it translates itto a curseforge entry.. it probably is because ids do not math so voodoo has no plan that you intended to replace it, you can ad filters for versions / filenames or similar to entries, with the coming kotlin-dsl this will be a lot clearer than it was using yaml

**Comment by lambdadog** [comment]
I wasn't using rewrite, thank you, wasn't actually aware it existed

**Comment by NikkyAI** [comment]
you have the options to restructure the yaml.. or to jump on the new kotlin-dsl

here is a example: https://github.com/NikkyAI/VoodooSamples/blob/master/src/TestPack.kt and here https://github.com/elytra/Voodoo/blob/rewrite/dsl/src/test/kotlin/voodoo/CotM.kt
but this still requires some boilerplate buildscript, i am trying to find ways to remove the boilerplate code and make the dependencies easier to use

**Comment by NikkyAI** [comment]
if this is still a issue, open a new one and link to this one
